#reference: https://github.com/prometheus-community/helm-charts
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prometheus
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus-community/kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 67.5.0
    helm:
      values: |
        rbac:
          create: true 
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true