apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-api
  labels:
    app: sample-api
spec:
  selector:
    matchLabels:
      app: sample-api
  endpoints:
    - port: http
      interval: 30s
      scrapeTimeout: 30s
      path: /metrics
      scheme: http